---
# tasks file for installDocker

- name: "Yum Update"
  command: sudo yum update -y
- name: "Yum Install Docker"
  command: sudo yum -y install docker
- name: "Start Docker"
  command: sudo service docker start
- name: "add ec2-user to docker group"
  command: sudo usermod -a -G docker ec2-user
- name: "Validate Docker Installed"
  command: docker info
~
~

